version: "3.5"
networks:
  avial:
    external: true

services:

  availnode:
    container_name: availnode
    image: availnode:latest
    ports:
      - 30333:30333
      - 9944:9944
    volumes:
      - ./output:/output availnode
    command:
      - "--dev"
      - "--rpc-methods=unsafe"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
    networks:
      - avial

  zkevm-sequencer:
    container_name: zkevm-sequencer
    image: zkevm-node
    ports:
      - 9092:9091 # needed if metrics enabled
      - 6060:6060
      - 6900:6900 # Data stream server
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
      - ZKEVM_NODE_MTCLIENT_URI=${ZKEVM_NODE_MTCLIENT_URI}
      - ZKEVM_NODE_EXECUTOR_URI=${ZKEVM_NODE_EXECUTOR_URI}
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
      - ./:/datastreamer
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequencer"
    networks:
      - avial




  zkevm-sequence-sender:
    container_name: zkevm-sequence-sender
    image: zkevm-node
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
      - ZKEVM_NODE_SEQUENCER_SENDER_ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
      - ZKEVM_NODE_MTCLIENT_URI=${ZKEVM_NODE_MTCLIENT_URI}
      - ZKEVM_NODE_EXECUTOR_URI=${ZKEVM_NODE_EXECUTOR_URI}
    volumes:
      - ./validium-node/test/sequencer.keystore:/pk/sequencer.keystore
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"
    networks:
      - avial




  zkevm-json-rpc:
    container_name: zkevm-json-rpc
    image: zkevm-node
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
      - ZKEVM_NODE_MTCLIENT_URI=${ZKEVM_NODE_MTCLIENT_URI}
      - ZKEVM_NODE_EXECUTOR_URI=${ZKEVM_NODE_EXECUTOR_URI}
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"
    networks:
      - avial

  zkevm-json-rpc-v1tov2:
    container_name: zkevm-json-rpc-v1tov2
    image: zkevm-node
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
      - ZKEVM_NODE_MTCLIENT_URI=${ZKEVM_NODE_MTCLIENT_URI}
      - ZKEVM_NODE_EXECUTOR_URI=${ZKEVM_NODE_EXECUTOR_URI}
      - ZKEVM_NODE_ETHERMAN_URL=http://zkevm-v1tov2-l1-network:8545
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis-v1tov2.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"
    networks:
      - avial

  zkevm-aggregator:
    container_name: zkevm-aggregator
    image: zkevm-node
    ports:
      - 50081:50081
      - 9093:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_AGGREGATOR_SENDER_ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
    volumes:
      - ./validium-node/test/sequencer.keystore:/pk/sequencer.keystore
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components aggregator"
    networks:
      - avial

  zkevm-sync:
    container_name: zkevm-sync
    image: zkevm-node
    ports:
      - 9095:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_MTCLIENT_URI=${ZKEVM_NODE_MTCLIENT_URI}
      - ZKEVM_NODE_EXECUTOR_URI=${ZKEVM_NODE_EXECUTOR_URI}
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"
    networks:
      - avial

  zkevm-eth-tx-manager:
    container_name: zkevm-eth-tx-manager
    image: zkevm-node
    ports:
      - 9094:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
    volumes:
      - ./validium-node/test/sequencer.keystore:/pk/sequencer.keystore
      - ./validium-node/test/aggregator.keystore:/pk/aggregator.keystore
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"
    networks:
      - avial

  zkevm-l2gaspricer:
    container_name: zkevm-l2gaspricer
    image: zkevm-node
    environment:
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./validium-node/test/test.keystore:/pk/keystore
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components l2gaspricer"
    networks:
      - avial


  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./validium-node/db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
    networks:
      - avial

  zkevm-pool-db:
    container_name: zkevm-pool-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"
    networks:
      - avial

  zkevm-event-db:
    container_name: zkevm-event-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5435:5432
    volumes:
      - ./validium-node/db/scripts/init_event_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_db
    command:
      - "postgres"
      - "-N"
      - "500"
    networks:
      - avial




  zkevm-mock-l1-network:
    container_name: zkevm-mock-l1-network
    image: hermeznetwork/geth-cdk-validium-contracts:20240420 #0xpolygon/cdk-validium-contracts:forkId8
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"
    networks:
      - avial

  zkevm-v1tov2-l1-network:
    container_name: zkevm-v1tov2-l1-network
    image: hermeznetwork/geth-cdk-validium-contracts:20240420
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"
    networks:
      - avial

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:v5.0.6
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./validium-node/test/config/test.prover.config.json:/usr/src/app/config.json
    environment:
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    command: >
      zkProver -c /usr/src/app/config.json
    networks:
      - avial

  zkevm-approve:
    container_name: zkevm-approve
    image: zkevm-node
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
    volumes:
      - ./validium-node/test/sequencer.keystore:/pk/keystore
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --key-store-path /pk/keystore --pw testonly --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml"
    networks:
      - avial



  zkevm-permissionless-db:
    container_name: zkevm-permissionless-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5434:5432
    volumes:
      - ./validium-node/db/scripts/single_db_server.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command:
      - "postgres"
      - "-N"
      - "500"
    networks:
      - avial

  zkevm-permissionless-node:
    container_name: zkevm-permissionless-node
    image: zkevm-node
    ports:
      - 8125:8125
    environment:
      - ZKEVM_NODE_ISTRUSTEDSEQUENCER=false
      - ZKEVM_NODE_STATE_DB_USER=test_user
      - ZKEVM_NODE_STATE_DB_PASSWORD=test_password
      - ZKEVM_NODE_STATE_DB_NAME=state_db
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-permissionless-db
      - ZKEVM_NODE_POOL_DB_USER=test_user
      - ZKEVM_NODE_POOL_DB_PASSWORD=test_password
      - ZKEVM_NODE_POOL_DB_NAME=pool_db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-permissionless-db
      - ZKEVM_NODE_RPC_PORT=8125
      - ZKEVM_NODE_RPC_SEQUENCERNODEURI=http://zkevm-json-rpc:8123
      - ZKEVM_NODE_MTCLIENT_URI=zkevm-permissionless-prover:50061
      - ZKEVM_NODE_EXECUTOR_URI=zkevm-permissionless-prover:50071
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"rpc,synchronizer\""
    networks:
      - avial

  zkevm-permissionless-prover:
    container_name: zkevm-permissionless-prover
    image: hermeznetwork/zkevm-prover:v5.0.6
    ports:
      # - 50058:50058 # Prover
      - 50059:50052 # Mock prover
      - 50068:50061 # MT
      - 50078:50071 # Executor
    volumes:
      - ./validium-node/test/config/test.permissionless.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    networks:
      - avial

  zkevm-metrics:
    image: prom/prometheus:v2.39.1
    container_name: zkevm-metrics
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./validium-node/config/metrics/prometheus:/etc/prometheus
    networks:
      - avial

  zkevm-sh:
    container_name: zkevm-sh
    image: zkevm-node
    stdin_open: true
    tty: true
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
      - ./validium-node/test/config/test.avail.config.json:/app/avail-config.json
      - ./validium-node/test/config/test.nubit.config.json:/app/nubit-config.json
    command:
      - "/bin/sh"
    networks:
      - avial

  zkevm-node-forced-DAC:
    container_name: zkevm-node-forced-DAC
    image: zkevm-node
    ports:
      - 8125:8125
    environment:
      - ZKEVM_NODE_ISTRUSTEDSEQUENCER=false
      - ZKEVM_NODE_STATEDB_USER=test_user
      - ZKEVM_NODE_STATEDB_PASSWORD=test_password
      - ZKEVM_NODE_STATEDB_NAME=state_db
      - ZKEVM_NODE_STATEDB_HOST=zkevm-permissionless-db
      - ZKEVM_NODE_POOL_DB_USER=test_user
      - ZKEVM_NODE_POOL_DB_PASSWORD=test_password
      - ZKEVM_NODE_POOL_DB_NAME=pool_db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-permissionless-db
      - ZKEVM_NODE_RPC_PORT=8125
      - ZKEVM_NODE_RPC_SEQUENCERNODEURI=http://zkevm-node-json-rpc:8123
      - ZKEVM_NODE_SYNCHRONIZER_TRUSTEDSEQUENCERURL=http://you-cant-touch-this:8123
      - ZKEVM_NODE_MTCLIENT_URI=zkevm-permissionless-prover:50061
      - ZKEVM_NODE_EXECUTOR_URI=zkevm-permissionless-prover:50071
    volumes:
      - ./validium-node/test/config/test.node.config.toml:/app/config.toml
      - ./validium-node/test/config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"rpc,synchronizer\""
    networks:
      - avial

  zkevm-data-node-db:
    container_name: zkevm-data-node-db
    restart: unless-stopped
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"
    networks:
      - avial
