DOCKERCOMPOSE := docker-compose -f docker-compose.yml
DOCKERCOMPOSESTATEDB := zkevm-state-db
DOCKERCOMPOSEPOOLDB := zkevm-pool-db
DOCKERCOMPOSEEVENTDB := zkevm-event-db
DOCKERCOMPOSENETWORK := zkevm-mock-l1-network
DOCKERCOMPOSEZKPROVER := zkevm-prover
DOCKERCOMPOSENODEAPPROVE := zkevm-approve
DOCKERCOMPOSEAPPSYNC := zkevm-sync
DOCKERCOMPOSEAPPETHTXMANAGER := zkevm-eth-tx-manager
DOCKERCOMPOSEAPPSEQ := zkevm-sequencer
DOCKERCOMPOSEAPPSEQSENDER := zkevm-sequence-sender
DOCKERCOMPOSEAPPL2GASP := zkevm-l2gaspricer
DOCKERCOMPOSEAPPAGG := zkevm-aggregator
DOCKERCOMPOSEAPPRPC := zkevm-json-rpc
DOCKERCOMPOSEAVAILNODE := availnode

RUNSTATEDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSESTATEDB)
RUNPOOLDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEPOOLDB)
RUNEVENTDB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEEVENTDB)

RUNL1NETWORK := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSENETWORK)


RUNZKPROVER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEZKPROVER)
RUNAPPROVE := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSENODEAPPROVE)

RUNSYNC := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPSYNC)
RUNETHTXMANAGER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPETHTXMANAGER)
RUNSEQUENCER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPSEQ)
RUNSEQUENCESENDER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPSEQSENDER)
RUNL2GASPRICER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPL2GASP)
RUNAGGREGATOR := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPAGG)
RUNJSONRPC := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAPPRPC)

RUNAVAILNODE := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSEAVAILNODE)


STOP := $(DOCKERCOMPOSE) down --remove-orphans

.PHONY: runavailnode
runavailnode: ## Runs a full node


.PHONY: run
run: ## Runs a full node
	@./run.sh
	sleep 3
	@echo "Generating genesis"
	@./genesis.sh
#	sleep 3
#	@echo "Starting services"
#	$(RUNAVAILNODE)
#	sleep 10
#	$(RUNSTATEDB)
#	$(RUNPOOLDB)
#	$(RUNEVENTDB)
#	$(RUNL1NETWORK)
#	sleep 1
#	$(RUNZKPROVER)
#	$(RUNAPPROVE)
#	sleep 3
#	$(RUNSYNC)
#	sleep 4
#	$(RUNETHTXMANAGER)
#	$(RUNSEQUENCER)
#	$(RUNSEQUENCESENDER)
#	$(RUNL2GASPRICER)
#	$(RUNAGGREGATOR)
#	$(RUNJSONRPC)


.PHONY: stop
stop: ## Stops all services
	cd ./validium-node/test && make stop


build-docker: ## Builds a docker image with the node binary
	docker build -t zkevm-node -f ./validium-node/Dockerfile .
